"""
Query Planner Agent.
Decomposes complex enterprise user queries into structured sub-queries and retrieval plans.
"""

import re
from typing import List, Dict, Any
from pydantic import BaseModel, Field


class SubQuery(BaseModel):
    """Sub-query generated by the query planner."""
    subquery_id: str
    query_text: str
    target_intent: str  # 'fact_lookup', 'policy_rule', 'comparison', 'general'
    keywords: List[str]


class QueryPlan(BaseModel):
    """Execution plan generated for an enterprise query."""
    original_query: str
    is_complex: bool
    subqueries: List[SubQuery]
    plan_notes: str


class QueryPlannerAgent:
    """
    Decomposes multi-faceted questions (e.g. comparisons, multiple constraints)
    into parallelizable sub-queries for precision retrieval.
    """

    def plan_query(self, query: str) -> QueryPlan:
        """Analyzes query complexity and produces an execution plan."""
        cleaned_query = query.strip()
        
        # Check for conjunctions and comparative clauses
        is_comparative = bool(re.search(r"\b(compare|difference between|versus|vs|both|and also|as well as)\b", cleaned_query, re.IGNORECASE))
        has_multiple_questions = bool(re.search(r"[?].+[?]", cleaned_query) or re.search(r"\band\b.*\bhow\b", cleaned_query, re.IGNORECASE))
        
        is_complex = is_comparative or has_multiple_questions

        subqueries: List[SubQuery] = []

        if is_complex:
            # Decompose along clauses or 'and' conjunctions
            clauses = re.split(r"\band\b|\bversus\b|\bvs\b|\bcompare\b|\?", cleaned_query, flags=re.IGNORECASE)
            valid_clauses = [c.strip() for c in clauses if len(c.strip().split()) >= 2]

            for idx, clause in enumerate(valid_clauses):
                subqueries.append(
                    SubQuery(
                        subquery_id=f"sq_{idx+1:02d}",
                        query_text=clause,
                        target_intent="comparison" if is_comparative else "fact_lookup",
                        keywords=self._extract_keywords(clause)
                    )
                )
        
        # Fallback to single atomic subquery if decomposition yields empty or single
        if not subqueries:
            subqueries.append(
                SubQuery(
                    subquery_id="sq_01",
                    query_text=cleaned_query,
                    target_intent="fact_lookup",
                    keywords=self._extract_keywords(cleaned_query)
                )
            )

        return QueryPlan(
            original_query=cleaned_query,
            is_complex=is_complex,
            subqueries=subqueries,
            plan_notes=f"Generated {len(subqueries)} retrieval target(s) for query execution."
        )

    def _extract_keywords(self, text: str) -> List[str]:
        """Extracts significant keywords, stripping common stop words."""
        stop_words = {
            "what", "is", "the", "how", "to", "in", "and", "or", "for", "a",
            "an", "of", "with", "does", "do", "are", "can", "please", "tell", "me"
        }
        tokens = re.findall(r"\b\w+\b", text.lower())
        return [t for t in tokens if t not in stop_words and len(t) > 2]


# Global planner instance
global_query_planner = QueryPlannerAgent()
