"""
Response Synthesizer Agent.
Builds grounded prompts, directs sovereign LLM inference, and formats EU AI Act transparent citations.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from src.rag.vector_store import SearchResult
from src.llm.sovereign_client import SovereignLLMClient, LLMResponse, global_sovereign_llm


class Citation(BaseModel):
    """Source citation reference for EU AI Act transparency."""
    citation_id: str
    doc_id: str
    doc_title: str
    section: str
    chunk_id: str
    relevance_score: float


class SynthesizedOutput(BaseModel):
    """Grounded output generated by the synthesizer."""
    answer: str
    citations: List[Citation]
    model_name: str
    tokens_used: int
    is_sovereign: bool
    eu_transparency_disclaimer: str


class ResponseSynthesizerAgent:
    """
    Synthesizes compliant responses grounded in retrieved context passages
    with mandatory citation mappings and watermarking.
    """

    EU_AI_ACT_DISCLAIMER = (
        "🇪🇺 EU AI Act Transparency Notice: This response was generated by an autonomous AI system "
        "and grounded strictly on verified enterprise documentation. Content is auditable under EU AI Act Art. 13."
    )

    def __init__(self, llm_client: Optional[SovereignLLMClient] = None):
        self.llm_client = llm_client or global_sovereign_llm

    def _build_system_prompt(self) -> str:
        return (
            "You are an enterprise AI assistant operating under strict EU GDPR and EU AI Act compliance standards.\n"
            "Rules:\n"
            "1. Answer ONLY using the factual context snippets provided.\n"
            "2. Cite every factual assertion with its corresponding source tag: [Doc Title: Section].\n"
            "3. If the context does not contain enough information, state clearly that you do not have sufficient data.\n"
            "4. NEVER extrapolate or fabricate unverified statistics or facts.\n"
            "5. Maintain all pseudonym tags (<PERSON_01>, <IBAN_01>, etc.) without alteration."
        )

    def _build_user_prompt(self, query: str, context_chunks: List[SearchResult]) -> str:
        context_blocks = []
        for c in context_chunks:
            title = c.metadata.get("title", "Enterprise Document")
            context_blocks.append(
                f"[Doc: {title} | Section: {c.section_title}]\n{c.content}\n"
            )
        formatted_context = "\n---\n".join(context_blocks)

        return (
            f"User Question: {query}\n\n"
            f"Enterprise Ground Truth Context:\n"
            f"{formatted_context}\n\n"
            f"Provide a concise, comprehensive answer citing the sources above."
        )

    async def synthesize(
        self,
        query: str,
        context_chunks: List[SearchResult]
    ) -> SynthesizedOutput:
        """Executes sovereign LLM generation and builds citation bibliography."""
        system_prompt = self._build_system_prompt()
        user_prompt = self._build_user_prompt(query, context_chunks)

        llm_resp: LLMResponse = await self.llm_client.generate_response(
            system_prompt=system_prompt,
            user_prompt=user_prompt
        )

        citations: List[Citation] = []
        for idx, c in enumerate(context_chunks):
            title = c.metadata.get("title", "Enterprise Document")
            citations.append(
                Citation(
                    citation_id=f"cit_{idx+1:02d}",
                    doc_id=c.doc_id,
                    doc_title=title,
                    section=c.section_title,
                    chunk_id=c.chunk_id,
                    relevance_score=c.score
                )
            )

        return SynthesizedOutput(
            answer=llm_resp.content,
            citations=citations,
            model_name=llm_resp.model,
            tokens_used=llm_resp.tokens_used,
            is_sovereign=llm_resp.is_sovereign,
            eu_transparency_disclaimer=self.EU_AI_ACT_DISCLAIMER
        )


# Global synthesizer agent instance
global_synthesizer_agent = ResponseSynthesizerAgent()
